### ISSUE TITLE
Looping over json

### ISSUE THREAD

**Issue by virajsoni06** [argyleink/grunt-fetch-json#1]
Hi @argyleink, this is exactly what I am looking for, for one of my projects. However, before I get started with it, I want to know, how can I loop through a paginated json file and store data into one json file?

**Comment by argyleink** [comment]
so you want to pull multiple json files down from a remote source, then merge it into 1 master json file? you could fork this and modify what happens are all the promises resolve. havent tried to merge or create a new json file from many json files.

**Comment by virajsoni06** [comment]
Yes. But the problem is, there is no definitive number of json files. They can increase overtime.
Let me have a go at it. I'll see what I can do. Thanks
