### ISSUE TITLE
Local Npm module "fetchJson" not found

### ISSUE THREAD

**Issue by stevetrask** [argyleink/grunt-fetch-json#2]
I am hitting an issue where the error is:

Local Npm module "fetchJson" not found. Is it installed?

Do you have any ideas on this? is fetchJson maintained still?

Thanks

**Comment by argyleink** [comment]
its still working. 

sounds like this grunt plugin isnt installed in your dev env

**Comment by stevetrask** [comment]
I have run all the commands etc to install it, while trying to look for the npm module itself I have hit a 404 from the google results https://www.npmjs.com/package/fetchjson/tutorial 

Does the npm module exist? I am thinking it is okay for previous installs but not new

**Comment by argyleink** [comment]
this repo is for the npm module https://www.npmjs.com/package/grunt-fetch-json
maybe logging an issue against the wrong tool?

**Comment by stevetrask** [comment]
Sorry I could not get to the bottom of this but have found another way to achieve the goal, thanks for the help
